In [1]:
print("Hola")

Hola


# Programa basico en python

In [2]:
import numpy as np

In [3]:
#Crear un arreglo ndarray, lleno de ceros

ceros= np.zeros(10)

ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
unos= np.ones((5, 5))

unos

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Crear ndarray con datos aleatorios

In [8]:
aleatorio= np.random.rand(5,5)
aleatorio

array([[0.67437115, 0.36343509, 0.37509645, 0.17518964, 0.91640657],
       [0.85871917, 0.01027484, 0.98900621, 0.20623316, 0.53891743],
       [0.28512523, 0.01034975, 0.00424255, 0.74141868, 0.46500325],
       [0.83586289, 0.83366761, 0.93071192, 0.83987941, 0.59085297],
       [0.88287188, 0.85060672, 0.25276259, 0.26932652, 0.02248069]])

# Operaciones con ndarray

In [9]:
suma= np.sum(aleatorio)
suma

12.922812375306142

In [10]:
media= np.mean(aleatorio)
media

0.5169124950122457

In [12]:
mediana= np.median(aleatorio)
mediana

0.5389174302133943

In [13]:
desviacion= np.std(aleatorio)
desviacion

0.33276804386851877

In [14]:
seno= np.sin(aleatorio)
seno

array([[0.62440624, 0.35548703, 0.36636227, 0.17429488, 0.79341951],
       [0.75700628, 0.01027466, 0.83548028, 0.20477435, 0.51320716],
       [0.28127763, 0.01034956, 0.00424254, 0.67533488, 0.44842571],
       [0.74187539, 0.74040158, 0.80204535, 0.74456262, 0.55706959],
       [0.77256552, 0.75168069, 0.25007972, 0.2660823 , 0.0224788 ]])

In [15]:
grados= np.rad2deg(aleatorio)
grados

array([[38.63862057, 20.82329656, 21.49144331, 10.03762689, 52.50622852],
       [49.20098443,  0.58870512, 56.66588175, 11.81628978, 30.87769426],
       [16.3364725 ,  0.59299687,  0.24308022, 42.48016113, 26.64272391],
       [47.8914161 , 47.76563549, 53.32586477, 48.12154534, 33.85338172],
       [50.5848325 , 48.73617515, 14.48222991, 15.43127312,  1.28804863]])

In [16]:
orden= np.sort(aleatorio)
orden

array([[0.17518964, 0.36343509, 0.37509645, 0.67437115, 0.91640657],
       [0.01027484, 0.20623316, 0.53891743, 0.85871917, 0.98900621],
       [0.00424255, 0.01034975, 0.28512523, 0.46500325, 0.74141868],
       [0.59085297, 0.83366761, 0.83586289, 0.83987941, 0.93071192],
       [0.02248069, 0.25276259, 0.26932652, 0.85060672, 0.88287188]])

# Datos espaciales
Es aquel que puede ser asociado a una posicion en el espacio, ya sea en plano 2D, 3D o n-dimensional.

In [20]:
import matplotlib.pyplot as plt 

#Simular un conjunto de datos que representen la elevacion puntual en un terrero

#crear un conjunto de datos de prueba
elevacion= np.random.randint(0, 3000, size=(100,100))


AttributeError: module 'matplotlib.pyplot' has no attribute 'imgshow'

In [22]:
#muestra los datos de un arreglo y cmap= muestra un mapa de color
plt.imshow(elevacion, cmap="terrain") 
plt.colorbar(label= "Altura (m)")
plt.show()

## Taller
Crear un ndarray de 2 dimensiones con la estatura de cada estudiante

calcular la media, mediana y desviacion estandar y graficar la data de estatura del grupo

In [49]:
miLista= ([1.88, 1.60, 1.60, 1.60, 1.60, 1.60, 1.65, 1.59, 1.73],[1.54, 1.72, 1.74, 1.80, 1.75, 1.75, 1.69, 1.75, 1.60])
estaturas = np.array(miLista)
print(estaturas)
media= np.mean(estaturas)
print(media)
mediana= np.median(estaturas)
print(mediana)
desviacion= np.std(estaturas)
print(desviacion)
plt.imshow(estaturas, cmap="BuPu")
plt.colorbar(label="Estatura (m)")
plt.show()

[[1.88 1.6  1.6  1.6  1.6  1.6  1.65 1.59 1.73]
 [1.54 1.72 1.74 1.8  1.75 1.75 1.69 1.75 1.6 ]]
1.6772222222222224
1.67
0.08936849777780602
